name: Publish Images
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: Carlos9905
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build py3.10-odoo16.0
      run: |
        docker buildx create --use --name mybuilder
        docker buildx build \
          --platform linux/amd64 \
          --tag ghcr.io/Carlos9905/algorit-ci-odoo:py3-10-odoo16-0:latest \
          --build-arg python_version=3.10 \
          --build-arg odoo_version=16.0 \
          --build-arg codename=jammy \
          --push .
